{
 "title": "Azure / Insights / Networks",
 "description": "Using Azure Monitor data source, this dashboard provides insights for network monitoring. This monitoring is available for the following Azure services: Front Door, Traffic Manager, Application Gateways and Load Balancers.",
 "tags": [ "Azure-managed" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "am_ds",
    "label": "Datasource",
    "query": "grafana-azure-monitor-datasource"
   },
   {
    "name": "loadbalancer",
    "label": "Namespaces",
    "query": "microsoft.network/loadbalancers"
   },
   {
    "name": "applicationgateway",
    "query": "microsoft.network/applicationgateways"
   },
   {
    "name": "trafficmanager",
    "query": "microsoft.network/trafficmanagerprofiles"
   },
   { "name": "frontdoor", "query": "microsoft.cdn/profiles" },
   {
    "name": "sub",
    "label": "Subscription",
    "query": {}
   },
   {
    "name": "rg",
    "label": "Resource Group",
    "query": {}
   },
   {
    "name": "resloadbalancer",
    "label": "Load Balancer",
    "query": {}
   },
   {
    "name": "resapplicationgateway",
    "label": "Application Gateways",
    "query": {}
   },
   {
    "name": "restrafficmanager",
    "label": "Traffic Managers",
    "query": {}
   },
   {
    "name": "resfrontdoor",
    "label": "Front doors",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Front Door - ${resfrontdoor}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "resfrontdoor" },
  {
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "azureResourceGraph": {
      "query": "resources\r\n| where tolower(subscriptionId) == tolower(\"$sub\") and tolower(resourceGroup) == tolower(\"$rg\") and tolower(name) == tolower($resfrontdoor)\r\n| project Name=name, sku.name, location, subscriptionId\r\n| join kind=inner(\r\n    resourcecontainers\r\n        | where type == \"microsoft.resources/subscriptions\" and tolower(subscriptionId) == tolower(\"$sub\")\r\n        | project subscriptionId, Subscription = name\r\n) on subscriptionId\r\n| project-away subscriptionId, subscriptionId1\r\n| join kind=leftouter(\r\n    alertsmanagementresources\r\n        | where tolower(properties.context.context.resourceName) == tolower($resfrontdoor)\r\n        | summarize count() by tostring(properties.context.context.resourceName), subscriptionId\r\n        | project properties_context_context_resourceName, count_, subscriptionId\r\n) on $left.Name == $right.properties_context_context_resourceName\r\n| project Name, Alerts=iff(isnull(count_), 0, count_), SKU=tostring(sku_name), Subscription, Location=location\r\n"
     },
     "subscriptions": [ "$sub" ]
    }
   ]
  },
  {
   "title": "Origin Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "dimensionFilters": [],
      "metricDefinition": "$frontdoor",
      "metricName": "OriginLatency",
      "metricNamespace": "$frontdoor",
      "resourceGroup": "$rg",
      "resourceName": "$resfrontdoor",
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 6 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "dimensionFilters": [],
      "metricDefinition": "$frontdoor",
      "metricName": "RequestCount",
      "metricNamespace": "$frontdoor",
      "resourceGroup": "$rg",
      "resourceName": "$resfrontdoor",
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Total Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 6 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "dimensionFilters": [],
      "metricDefinition": "$frontdoor",
      "metricName": "TotalLatency",
      "metricNamespace": "$frontdoor",
      "resourceGroup": "$rg",
      "resourceName": "$resfrontdoor",
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Origin Health Percentage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 6 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "dimensionFilters": [],
      "metricDefinition": "$frontdoor",
      "metricName": "OriginHealthPercentage",
      "metricNamespace": "$frontdoor",
      "resourceGroup": "$rg",
      "resourceName": "$resfrontdoor",
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Traffic Manager - ${restrafficmanager}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "repeat": "restrafficmanager",
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "azureMonitor": {
        "dimensionFilters": [],
        "timeGrain": "auto"
       },
       "azureResourceGraph": {
        "query": "resources\r\n| where tolower(subscriptionId) == tolower(\"$sub\") and tolower(resourceGroup) == tolower(\"$rg\") and tolower(name) == tolower($restrafficmanager)\r\n| project Name=name, sku.name, location, subscriptionId\r\n| join kind=inner(\r\n    resourcecontainers\r\n        | where type == \"microsoft.resources/subscriptions\" and tolower(subscriptionId) == tolower(\"$sub\")\r\n        | project subscriptionId, Subscription = name\r\n) on subscriptionId\r\n| project-away subscriptionId, subscriptionId1\r\n| join kind=leftouter(\r\n    alertsmanagementresources\r\n        | where tolower(properties.context.context.resourceName) == tolower($restrafficmanager)\r\n        | summarize count() by tostring(properties.context.context.resourceName), subscriptionId\r\n        | project properties_context_context_resourceName, count_, subscriptionId\r\n) on $left.Name == $right.properties_context_context_resourceName\r\n| project Name, Alerts=iff(isnull(count_), 0, count_), SKU=tostring(sku_name), Subscription, Location=location\r\n"
       },
       "subscriptions": [ "$sub" ]
      }
     ]
    },
    {
     "title": "Endpoint Status by Endpoint",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Total",
        "dimensionFilters": [],
        "metricDefinition": "$trafficmanager",
        "metricName": "ProbeAgentCurrentEndpointStateByProfileResourceId",
        "metricNamespace": "$trafficmanager",
        "resourceGroup": "$rg",
        "resourceName": "$restrafficmanager",
        "timeGrain": "auto"
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "title": "Queries by Endpoint Returned",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Maximum",
        "dimensionFilters": [],
        "metricDefinition": "$trafficmanager",
        "metricName": "QpsByEndpoint",
        "metricNamespace": "$trafficmanager",
        "resourceGroup": "$rg",
        "resourceName": "$restrafficmanager",
        "timeGrain": "auto"
       },
       "subscription": "$sub"
      }
     ]
    }
   ]
  },
  {
   "title": "Application Gateways - ${resapplicationgateway}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "repeat": "resapplicationgateway",
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 27 },
     "targets": [
      {
       "azureMonitor": {
        "dimensionFilters": [],
        "timeGrain": "auto"
       },
       "azureResourceGraph": {
        "query": "resources\r\n| where tolower(subscriptionId) == tolower(\"$sub\") and tolower(resourceGroup) == tolower(\"$rg\") and tolower(name) == tolower($resapplicationgateway)\r\n| project Name=name, sku.name, location, subscriptionId\r\n| join kind=inner(\r\n    resourcecontainers\r\n        | where type == \"microsoft.resources/subscriptions\" and tolower(subscriptionId) == tolower(\"$sub\")\r\n        | project subscriptionId, Subscription = name\r\n) on subscriptionId\r\n| project-away subscriptionId, subscriptionId1\r\n| join kind=leftouter(\r\n    alertsmanagementresources\r\n        | where tolower(properties.context.context.resourceName) == tolower($resapplicationgateway)\r\n        | summarize count() by tostring(properties.context.context.resourceName), subscriptionId\r\n        | project properties_context_context_resourceName, count_, subscriptionId\r\n) on $left.Name == $right.properties_context_context_resourceName\r\n| project Name, Alerts=iff(isnull(count_), 0, count_), SKU=tostring(sku_name), Subscription, Location=location\r\n"
       },
       "subscriptions": [ "$sub" ]
      }
     ]
    },
    {
     "title": "Throughput",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 29 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Average",
        "dimensionFilters": [],
        "metricDefinition": "$applicationgateway",
        "metricName": "Throughput",
        "metricNamespace": "$applicationgateway",
        "resourceGroup": "$rg",
        "resourceName": "$resapplicationgateway",
        "timeGrain": "auto"
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "title": "Unhealthy Host Count",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 29 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Average",
        "dimensionFilters": [],
        "metricDefinition": "$applicationgateway",
        "metricName": "UnhealthyHostCount",
        "metricNamespace": "$applicationgateway",
        "resourceGroup": "$rg",
        "resourceName": "$resapplicationgateway",
        "timeGrain": "auto"
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "title": "Failed Requests",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 29 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Total",
        "dimensionFilters": [],
        "metricDefinition": "$applicationgateway",
        "metricName": "FailedRequests",
        "metricNamespace": "$applicationgateway",
        "resourceGroup": "$rg",
        "resourceName": "$resapplicationgateway",
        "timeGrain": "auto"
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "title": "Response Status",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 29 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Total",
        "dimensionFilters": [],
        "metricDefinition": "$applicationgateway",
        "metricName": "ResponseStatus",
        "metricNamespace": "$applicationgateway",
        "resourceGroup": "$rg",
        "resourceName": "$resapplicationgateway",
        "timeGrain": "auto"
       },
       "subscription": "$sub"
      }
     ]
    }
   ]
  },
  {
   "title": "Load Balancers - ${resloadbalancer}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "repeat": "resloadbalancer",
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 40 },
     "targets": [
      {
       "azureMonitor": {
        "dimensionFilters": [],
        "timeGrain": "auto"
       },
       "azureResourceGraph": {
        "query": "resources\r\n| where tolower(subscriptionId) == tolower(\"$sub\") and tolower(resourceGroup) == tolower(\"$rg\") and tolower(name) == tolower($resloadbalancer)\r\n| project Name=name, sku.name, location, subscriptionId\r\n| join kind=inner(\r\n    resourcecontainers\r\n        | where type == \"microsoft.resources/subscriptions\" and tolower(subscriptionId) == tolower(\"$sub\")\r\n        | project subscriptionId, Subscription = name\r\n) on subscriptionId\r\n| project-away subscriptionId, subscriptionId1\r\n| join kind=leftouter(\r\n    alertsmanagementresources\r\n        | where tolower(properties.context.context.resourceName) == tolower($resloadbalancer)\r\n        | summarize count() by tostring(properties.context.context.resourceName), subscriptionId\r\n        | project properties_context_context_resourceName, count_, subscriptionId\r\n) on $left.Name == $right.properties_context_context_resourceName\r\n| project Name, Alerts=iff(isnull(count_), 0, count_), SKU=tostring(sku_name), Subscription, Location=location\r\n"
       },
       "subscriptions": [ "$sub" ]
      }
     ]
    },
    {
     "title": "SYN Count",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 42 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Total",
        "dimensionFilters": [],
        "metricDefinition": "$loadbalancer",
        "metricName": "SYNCount",
        "metricNamespace": "$loadbalancer",
        "resourceGroup": "$rg",
        "resourceName": "$resloadbalancer",
        "timeGrain": "auto"
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "title": "SNAT Connection Count",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 42 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Total",
        "dimensionFilters": [],
        "metricDefinition": "$loadbalancer",
        "metricName": "SnatConnectionCount",
        "metricNamespace": "$loadbalancer",
        "resourceGroup": "$rg",
        "resourceName": "$resloadbalancer",
        "timeGrain": "auto"
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "title": "Data Path Availability",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 42 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Average",
        "dimensionFilters": [],
        "metricDefinition": "$loadbalancer",
        "metricName": "VipAvailability",
        "metricNamespace": "$loadbalancer",
        "resourceGroup": "$rg",
        "resourceName": "$resloadbalancer",
        "timeGrain": "auto"
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "title": "Health Probe Status",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 42 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Average",
        "dimensionFilters": [],
        "metricDefinition": "$loadbalancer",
        "metricName": "DipAvailability",
        "metricNamespace": "microsoft.network/loadbalancers",
        "resourceGroup": "$rg",
        "resourceName": "$resloadbalancer",
        "timeGrain": "auto"
       },
       "subscription": "$sub"
      }
     ]
    }
   ]
  }
 ]
}