{
 "title": "Azure Service Bus",
 "description": "https://github.com/yesoreyeram/grafana-azure-dashboards",
 "tags": [
  "azure",
  "templates"
 ],
 "time": { "from": "now-6h", "to": "now-1m" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Subscriptions",
    "label": "Subscriptions",
    "query": "grafana-azure-monitor-datasource"
   },
   { "name": "ResourceGroup", "label": "Resource Group", "query": "ResourceGroups()" },
   {
    "name": "ResourceName",
    "query": "ResourceNames($ResourceGroup,Microsoft.ServiceBus/namespaces)"
   }
  ]
 },
 "panels": [
  { "title": "Service Bus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Messages in Queue",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "e5b033d5-3fd9-490c-81f8-0bcf94171bdf"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "EntityName", "value": "EntityName" }
      ],
      "metricDefinition": "Microsoft.ServiceBus/namespaces",
      "metricName": "Messages",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "PT1M"
     }
    }
   ]
  },
  {
   "title": "Incoming Requests",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "appInsights": { "groupBy": "none", "metricName": "select", "timeGrainType": "auto" },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "EntityName", "value": "EntityName" }
      ],
      "metricDefinition": "Microsoft.ServiceBus/namespaces",
      "metricName": "IncomingRequests",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "1",
      "timeGrainUnit": "minute"
     }
    }
   ]
  },
  {
   "title": "Server Errors",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "appInsights": { "groupBy": "none", "metricName": "select", "timeGrainType": "auto" },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "EntityName", "value": "EntityName" }
      ],
      "metricDefinition": "Microsoft.ServiceBus/namespaces",
      "metricName": "ServerErrors",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "1",
      "timeGrainUnit": "minute"
     }
    }
   ]
  },
  {
   "title": "DEAD LETTER",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "e5b033d5-3fd9-490c-81f8-0bcf94171bdf"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Maximum",
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "EntityName", "value": "EntityName" }
      ],
      "metricDefinition": "Microsoft.ServiceBus/namespaces",
      "metricName": "DeadletteredMessages",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "Incoming Messages",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "appInsights": { "groupBy": "none", "metricName": "select", "timeGrainType": "auto" },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "EntityName", "value": "EntityName" }
      ],
      "metricDefinition": "Microsoft.ServiceBus/namespaces",
      "metricName": "IncomingMessages",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "1",
      "timeGrainUnit": "minute"
     }
    }
   ]
  },
  {
   "title": "Outgoing Messages",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "appInsights": { "groupBy": "none", "metricName": "select", "timeGrainType": "auto" },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "EntityName", "value": "EntityName" }
      ],
      "metricDefinition": "Microsoft.ServiceBus/namespaces",
      "metricName": "OutgoingMessages",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "1",
      "timeGrainUnit": "minute"
     }
    }
   ]
  },
  {
   "title": "Active messages in Queue",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "appInsights": { "groupBy": "none", "metricName": "select", "timeGrainType": "auto" },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "EntityName", "value": "EntityName" }
      ],
      "metricDefinition": "Microsoft.ServiceBus/namespaces",
      "metricName": "ActiveMessages",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "1",
      "timeGrainUnit": "minute"
     }
    }
   ]
  },
  {
   "title": "Successful Requests",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "appInsights": { "groupBy": "none", "metricName": "select", "timeGrainType": "auto" },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "EntityName", "value": "EntityName" }
      ],
      "metricDefinition": "Microsoft.ServiceBus/namespaces",
      "metricName": "SuccessfulRequests",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "1",
      "timeGrainUnit": "minute"
     }
    }
   ]
  },
  {
   "title": "User errors",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "appInsights": { "groupBy": "none", "metricName": "select", "timeGrainType": "auto" },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "EntityName", "value": "EntityName" }
      ],
      "metricDefinition": "Microsoft.ServiceBus/namespaces",
      "metricName": "UserErrors",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "1",
      "timeGrainUnit": "minute"
     }
    }
   ]
  },
  {
   "title": "Throttled requests",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "appInsights": { "groupBy": "none", "metricName": "select", "timeGrainType": "auto" },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "EntityName", "value": "EntityName" }
      ],
      "metricDefinition": "Microsoft.ServiceBus/namespaces",
      "metricName": "ThrottledRequests",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "1",
      "timeGrainUnit": "minute"
     }
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "appInsights": { "groupBy": "none", "metricName": "select", "timeGrainType": "auto" },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "dimension": null,
      "dimensionFilter": "*",
      "dimensions": [],
      "metricDefinition": "Microsoft.ServiceBus/namespaces",
      "metricName": "ActiveConnections",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "1",
      "timeGrainUnit": "minute"
     }
    }
   ]
  },
  {
   "title": "Size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 3 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "EntityName", "value": "EntityName" }
      ],
      "metricDefinition": "Microsoft.ServiceBus/namespaces",
      "metricName": "Size",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "Service Bus - Dead Letters By Topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "49694b22-63f5-470a-860e-b7ebd80e46b8"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "alias": "Dead letter messages - {{dimensionvalue}}",
      "dimension": "EntityName",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "EntityName", "value": "EntityName" }
      ],
      "metricDefinition": "Microsoft.ServiceBus/namespaces",
      "metricName": "DeadletteredMessages",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "PT1M"
     }
    }
   ]
  },
  {
   "title": "Service Bus - No of Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": { "groupBy": "none", "metricName": "select", "timeGrainType": "auto" },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "Successful Requests- {{dimensionvalue}}",
      "dimension": "EntityName",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "EntityName", "value": "EntityName" }
      ],
      "metricDefinition": "Microsoft.ServiceBus/namespaces",
      "metricName": "SuccessfulRequests",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "1",
      "timeGrainUnit": "minute"
     }
    },
    {
     "appInsights": { "groupBy": "none", "metricName": "select", "timeGrainType": "auto" },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "Incoming Requests -  {{dimensionvalue}}",
      "dimension": "EntityName",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "EntityName", "value": "EntityName" }
      ],
      "metricDefinition": "Microsoft.ServiceBus/namespaces",
      "metricName": "IncomingRequests",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "1",
      "timeGrainUnit": "minute"
     }
    },
    {
     "appInsights": { "groupBy": "none", "metricName": "select", "timeGrainType": "auto" },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "Throttled Requests - {{dimensionvalue}}",
      "dimension": "EntityName",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "EntityName", "value": "EntityName" }
      ],
      "metricDefinition": "Microsoft.ServiceBus/namespaces",
      "metricName": "ThrottledRequests",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "1",
      "timeGrainUnit": "minute"
     }
    }
   ]
  },
  {
   "title": "Service Bus - Incoming & Outgoing messages",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "appInsights": { "groupBy": "none", "metricName": "select", "timeGrainType": "auto" },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "Incoming Messages - {{dimensionvalue}}",
      "dimension": "EntityName",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "EntityName", "value": "EntityName" }
      ],
      "metricDefinition": "Microsoft.ServiceBus/namespaces",
      "metricName": "IncomingMessages",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "1",
      "timeGrainUnit": "minute"
     }
    },
    {
     "appInsights": { "groupBy": "none", "metricName": "select", "timeGrainType": "auto" },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "Outgoing Messages - {{dimensionvalue}}",
      "dimension": "EntityName",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "EntityName", "value": "EntityName" }
      ],
      "metricDefinition": "Microsoft.ServiceBus/namespaces",
      "metricName": "OutgoingMessages",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "1",
      "timeGrainUnit": "minute"
     }
    }
   ]
  },
  {
   "title": "Service Bus - Messages in Queue / Topic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "alias": "Messages - {{dimensionvalue}}",
      "dimension": "EntityName",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "EntityName", "value": "EntityName" }
      ],
      "metricDefinition": "Microsoft.ServiceBus/namespaces",
      "metricName": "Messages",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "Service Bus - Active Messages in Queue / Topic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "alias": "Active Messages - {{dimensionvalue}}",
      "dimension": "EntityName",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "EntityName", "value": "EntityName" }
      ],
      "metricDefinition": "Microsoft.ServiceBus/namespaces",
      "metricName": "ActiveMessages",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "Service Bus - Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "alias": "{{metric}} - {{resourcename}} - {{dimensionvalue}}",
      "dimension": "EntityName",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "EntityName", "value": "EntityName" }
      ],
      "metricDefinition": "Microsoft.ServiceBus/namespaces",
      "metricName": "Size",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "Service Bus - Active Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "appInsights": { "groupBy": "none", "metricName": "select", "timeGrainType": "auto" },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "{{metric}} - {{resourcename}}",
      "dimension": null,
      "dimensionFilter": "*",
      "dimensions": [],
      "metricDefinition": "Microsoft.ServiceBus/namespaces",
      "metricName": "ActiveConnections",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "1",
      "timeGrainUnit": "minute"
     }
    }
   ]
  },
  {
   "title": "Service Bus - Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": { "groupBy": "none", "metricName": "select", "timeGrainType": "auto" },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "{{metric}} - {{resourcename}}",
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "EntityName", "value": "EntityName" }
      ],
      "metricDefinition": "Microsoft.ServiceBus/namespaces",
      "metricName": "ServerErrors",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "1",
      "timeGrainUnit": "minute"
     }
    },
    {
     "appInsights": { "groupBy": "none", "metricName": "select", "timeGrainType": "auto" },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "{{metric}} - {{resourcename}}",
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "EntityName", "value": "EntityName" }
      ],
      "metricDefinition": "Microsoft.ServiceBus/namespaces",
      "metricName": "UserErrors",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "1",
      "timeGrainUnit": "minute"
     }
    }
   ]
  }
 ]
}