name: Azure Functions

on:
  workflow_dispatch:
    inputs:
      target_environment:
        description: 'GitHub environment to use for this deployment.'
        required: true
        default: 'dev'
        type: environment

permissions:
  contents: read

jobs:
  deploy-functions:
    uses: ./.github/workflows/azure-deploy.yml
    permissions:
      id-token: write
      contents: read
    with:
      target_environment: ${{ inputs.target_environment }}
      deployment_mode: apps-only
      deploy_target: talentfunctions
    secrets: inherit
